### PR TITLE
Close Issue #18

### PR DESCRIPTION
**Pull request by DavidWiesner**
Improve discovery of calendars in CalDAV using similar method described in 
http://code.google.com/p/sabredav/wiki/BuildingACalDAVClient#Discovery
1. check entered url is an calendar or calendar-collection
2. PROPFIND user-principal-url on url
3. PROPFIND calendar-home-set on user-principal-url
4. PROPFIND calendars on calendar-home-set

Tested with sabredav, owncloud, Yahoo.
Yahoo doesn't list calendars on PROPFIND in calendar-home-set. Therefore you have to entered the complete Calendar-URL for Yahoo. e.g.: 
https://caldav.calendar.yahoo.com/dav/<user-email>/Calendar/<calendarname>/

### CODE REVIEW

**Comment by gggard** [comment]
Thanks David for this patch, I test it and will integrate it as soon as possible to close these compatibility bugs.
I like also the refractoring you performed, that's the way it should be done but I did not had time for it...

**Comment by gggard** [comment]
I fetch your branch and it does not work anymore with davical (works with owncloud)... I chack this and keep you informed !

**Comment by DavidWiesner** [comment]
There were some Problems parsing the server response with sax. Please try the new version of this Pull Request.

**Comment by gggard** [comment]
Argh, still the same pb with davical, there is no calendar found...
I can provide you a test account on my install if it may help
Thanks a lot for your efforts !

I got the following logs :

03-03 19:37:55.991: V/SyncAdapter(626): onPerformSync() on gege with URL https://xxx/caldav.php/gege
03-03 19:37:56.869: E/CalendarHomeHandler(626): calendar-uri malformed: 
03-03 19:37:56.869: E/CalendarHomeHandler(626):  
03-03 19:37:56.869: E/CalendarHomeHandler(626):    /caldav.php/gege/home/
03-03 19:37:56.879: E/CalendarHomeHandler(626): calendar-uri malformed: 
03-03 19:37:56.879: E/CalendarHomeHandler(626):  
03-03 19:37:56.879: E/CalendarHomeHandler(626):    /caldav.php/gege/.out/
03-03 19:37:56.889: E/CalendarHomeHandler(626): calendar-uri malformed: 
03-03 19:37:56.889: E/CalendarHomeHandler(626):  
03-03 19:37:56.889: E/CalendarHomeHandler(626):    /caldav.php/gege/calendar-proxy-read/
03-03 19:37:56.929: E/CalendarHomeHandler(626): calendar-uri malformed: 
03-03 19:37:56.929: E/CalendarHomeHandler(626):  
03-03 19:37:56.929: E/CalendarHomeHandler(626):    /caldav.php/gege/calendar-proxy-write/
03-03 19:37:56.961: D/CaldavFacade(626): 0 calendars found in set https://xxx/caldav.php/gege
03-03 19:37:57.450: D/CaldavFacade(626): Found userPrincipal: https://xxx/caldav.php/gege/
03-03 19:37:57.809: D/CaldavFacade(626): 1 calendar-home-set found in https://xxxx/caldav.php/gege/
03-03 19:37:58.269: E/CalendarHomeHandler(626): calendar-uri malformed: 
03-03 19:37:58.269: E/CalendarHomeHandler(626):  
03-03 19:37:58.269: E/CalendarHomeHandler(626):    /caldav.php/gege/home/
03-03 19:37:58.269: E/CalendarHomeHandler(626): calendar-uri malformed: 
03-03 19:37:58.269: E/CalendarHomeHandler(626):  
03-03 19:37:58.269: E/CalendarHomeHandler(626):    /caldav.php/gege/.out/
03-03 19:37:58.280: E/CalendarHomeHandler(626): calendar-uri malformed: 
03-03 19:37:58.280: E/CalendarHomeHandler(626):  
03-03 19:37:58.280: E/CalendarHomeHandler(626):    /caldav.php/gege/calendar-proxy-read/
03-03 19:37:58.280: E/CalendarHomeHandler(626): calendar-uri malformed: 
03-03 19:37:58.280: E/CalendarHomeHandler(626):  
03-03 19:37:58.280: E/CalendarHomeHandler(626):    /caldav.php/gege/calendar-proxy-write/
03-03 19:37:58.309: D/CaldavFacade(626): 0 calendars found in set https://xxxx/caldav.php/gege/

**Comment by DavidWiesner** [comment]
Hi Gerald,
can you please check, you have chckout the right version of the pull request.
In my last commit i have add stringBuilder.setLength(0); in the startElement-Method in xml/CalendarsHandler.java. So can you please check if this lines are in your code.
I know i had some problems parsing the calendar-urls. The problem was i have also parsed some newlines that result in URIMalformed-Exception (as you can see in the log you have posted). 
regards,
david

**Comment by gggard** [comment]
Thanks David, I finally manage to make it work with Davical (added a trim at the right place, the URI was poluted by \n...)
I roll out the version right now, see what happen ;-)

**Comment by DavidWiesner** [comment]
what happend with the changes i made in CaldavFacade to recover the Calendars and working with SAX?

**Comment by gggard** [comment]
Ok I lost the fight against Git and your modification, I make a clean-up this evening and publish a new version with it
Sorry....

**Pull request merged**
