### PR TITLE
Added a few Properties

### PR DESCRIPTION
**Pull request by timoberger**
- TZID
- ORGANIZER
- ATTENDEE
- DURATION (as alternative to DTEND)
- VALARM
- Android Even - ALL_DAY (reworked)

### CODE REVIEW

**Comment by gggard** [comment]
Thanks I integrate this as son as possible!

**Comment by DavidWiesner** [comment]
Hy @timoberger ,
its just an recommendation but you should use [SyncStats SyncResults.stats](http://developer.android.com/reference/android/content/SyncStats.html) in SyncAdapter to store the numbers of deleted, updated and inserted Entries.
@gggard or @timoberger If you want to change that and have some time left;) you may also use SyncStats to handle Exceptions recommended in the official Android example-implementation of the [SyncAdapter](http://gitorious.org/0xdroid/development/blobs/00bf0f0296b6691a9ed93fa46eccf316f7b0222e/samples/SampleSyncAdapter/src/com/example/android/samplesync/syncadapter/SyncAdapter.java)

Please prefer native types over Object-Types in Java, so use `int` instead of `Integer`
regards, 
david

**Comment by timoberger** [comment]
@davey69 thanks for the remarks. I had been too long in the .net world.

**Comment by gggard** [comment]
@davey69, thanks for the idea on the SyncStat, I was wondering how to report stats and error, I will implement that

**Pull request merged**
